### ISSUE TITLE
Cohesive Interactables

### ISSUE THREAD

**Issue by CobeyH** [CobeyH/MothLight2D#107]
**Describe the solution you'd like**
We need to create a standard design language to make it clear which objects are interactable. I see several ways to do this, but I'm not sure which is best. Also it's possible a combination of them should be used.
- Change the mouse icon when an interactable is hovered. This is good because it's used in other applications so most users will be familiar with this pattern. However, it doesn't make it immediately obvious which elements are interactable without moving the mouse over every element in the scene.
- Create a throbbing effect so that interactable objects slowly get smaller and larger as in indicator that they are interactable. This would make it clear which objects are interactable immediately, but it may look weird and change the aesthetic of the game.
- Create a glowing halo around interactable objects. This has basically the same advantages and drawbacks of the previous point.

I see no harm in implementing point 1, no matter what other solutions we also implement on top of it.

**Comment by jpark052** [comment]
I like point 1 and 3. But maybe we dont have to make the halo effect permanent? We can probably display it for the first 5 seconds or something, and then delete it?

**Comment by CobeyH** [comment]
We have decided to try to implement a glow shader for interactable objects.
