### ISSUE TITLE
Setting Options Glow Too Much

### ISSUE THREAD

**Issue by jpark052** [CobeyH/MothLight2D#135]
Elements of setting menu (checkbox, dropdown menu, etc) seem to glow too much? I think the glow hinders the readability of the contents.

![Capture](https://user-images.githubusercontent.com/56705512/192681343-19235673-ed7b-4d61-b384-4806f3ce4839.PNG)

**Comment by CobeyH** [comment]
Very good point. Maybe we should just disable bloom all together for that menu.
