### ISSUE TITLE
Error Messages in Level 5

### ISSUE THREAD

**Issue by jpark052** [CobeyH/MothLight2D#137]
Some weird error messages are printed on console at level 5. I've never seen them before so I'm not sure what's causing the issue. However, I have not found an issue functionality wise.
![error level5](https://user-images.githubusercontent.com/56705512/192681928-58f56cfa-61d8-41a3-a851-d72f4395df92.PNG)

**Comment by CobeyH** [comment]
Can I get steps to reproduce this issue? I don't see any errors on level 5.

**Comment by jpark052** [comment]
those error messages were generated as soon as I started level 5. But I just tested this stage again, and I don't see those error messages anymore. wth? Sorry, I guess the bug has been fixed by itself or something lol

**Comment by CobeyH** [comment]
Okay, well I'm going to close this until we can duplicate the issue.
