### ISSUE TITLE
Checkpoints Not Updated

### ISSUE THREAD

**Issue by jpark052** [CobeyH/MothLight2D#138]
In level 6 (although I found this issue in level 6, I'm not sure if this could happen in other stages as well), when you complete the stage with less than 3 butterfly checkpoints, the result is not reflected on level selector screen. (i.e. even after you complete level 6, you don't see any butterfly under level6 button)

![level6 error](https://user-images.githubusercontent.com/56705512/192682586-45b92e49-8b91-498c-a8a9-7e168137e464.PNG)

![level6 -2](https://user-images.githubusercontent.com/56705512/192682595-cc1975e8-198b-40e3-940b-a50ad54031f4.PNG)

**Comment by CobeyH** [comment]
Unrelated issue, but does your screen not blur on level 6 when you complete the level?
![image](https://user-images.githubusercontent.com/32989729/192931295-81b8efad-f24a-48a0-8db5-e744a1acc3a8.png)

**Comment by jpark052** [comment]
I just tested again, and blur on level 6 complete screen still doesnt work for me. weird. Which branch are you on? I'm on main branch
