### ISSUE TITLE
Levels 7 - 10

### ISSUE THREAD

**Issue by jpark052** [CobeyH/MothLight2D#180]
The glass introduction level will be the new level 3. The trap light introduction level comes immediately after the two glass introduction levels.

This level goes immediately after the trap light introduction level.
![20221006_174238](https://user-images.githubusercontent.com/56705512/194462836-0750d5b6-eeba-4186-bb01-08e4ecc1cc70.jpg)
New Level 4
![20221006_180230](https://user-images.githubusercontent.com/56705512/194462842-32a8727e-e284-4935-b0ae-a0e15ed326d1.jpg)
![20221006_182153](https://user-images.githubusercontent.com/56705512/194462845-db968bdc-35ca-4405-837e-facfc29c8bc6.jpg)
![20221006_173116](https://user-images.githubusercontent.com/56705512/194462847-36290833-a855-4b1f-8a29-47d955994993.jpg)

**Comment by CobeyH** [comment]
Resolved by #183 and #182
