### ISSUE TITLE
Gap in Tile Map

### ISSUE THREAD

**Issue by TruestWaffle** [CobeyH/MothLight2D#187]
**Describe the bug**
Gap in tile map when wall tiles are attached to black tiles. 

**To Reproduce**
1. Go to level 3
2. Zoom in and out without grid on
3. Observe gap in hanging wall on left of level

**Expected behaviour**
No gap should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/108950863/195714828-a94857c6-9c61-4312-9686-9c95eb51bdca.png)

**Comment by CobeyH** [comment]
![image](https://user-images.githubusercontent.com/32989729/195714541-2ce6d881-a1b5-422f-8bd2-059da8492fb1.png)
 Context for level 3
