### ISSUE TITLE
Link Lights

### ISSUE THREAD

**Issue by TruestWaffle** [CobeyH/MothLight2D#193]
**Describe the solution you'd like**
The ability for the player or level creator to link lights so they turn on and off together.

This would allow level designers to force control over puzzles, working the player into trickier 'this so that' situations where logical compromise will be needed.

It will give the player the ability to link certain lights for better control of the Moths, being able to precisely place them in mid air.

**Comment by CobeyH** [comment]
We implemented game slowdown instead of this. Closing this issue.
