### ISSUE TITLE
Thorns

### ISSUE THREAD

**Issue by TruestWaffle** [CobeyH/MothLight2D#215]
**Describe the solution you'd like**
Use the Thorn assets that are present in our textures to create barriers. This would allow level designers to make the player carefully place the Moths before moving through the map, teaching greater depth in the puzzle system.

It would also allow designers to dress up the danger lights more, creating bramble thickets around them.

**Comment by CobeyH** [comment]
I know that we are trying to slow feature development until more levels are complete. However, this feature should be very easy to implement since it's basically just a trap light without a light attached to it. I'm going to green-light this one.
