### ISSUE TITLE
Repulsive Lights

### ISSUE THREAD

**Issue by TruestWaffle** [CobeyH/MothLight2D#216]
**Describe the solution you'd like**
Some kind of interactable or inert object that pushes the moths away (or repels them?).

Possibly a wind tunnel or breeze that could move the moths continuously, requiring the player to plan ahead before placing the moths into the current. 

Possibly a "anti-light" that repels instead of attracts. Maybe bug repellant? Maybe a flower? Some naturally in nature act as bug repellent. This would create a 'push-and-pull' mechanical tool set for the player, to add a little variety in strategy to completing levels.

**Comment by CobeyH** [comment]
Very interesting idea. I think this would work quite well in our current game. Perhaps this should be a autumn mechanic?
